title: SnickerBuzz - Variety Within
email: saquib.ahmad9898@gmail.com
name: SnickerBuzz
description: SnickerBuzz gets to you the latest movies with various genre like Action, Crime, Drama, Biograhy to download and watch them at ease.
markdown: kramdown
thumbnail: "images/logo.png"
author: Syed Saquib Ahmad
excerpt_separator: "<!--more-->"
url: https://snickerbuzz.com
enforce_ssl: snickerbuzz.com
plugins:
  - jekyll-feed