title: SnickerBuzz
email: saquib.ahmad9898@gmail.com
description: SnickerBuzz try to provide all sort of entertainment and knowledge you need to have in your daily life...
markdown: kramdown
author: Syed Saquib Ahmad
excerpt_separator: "<!--more-->"
plugins:
  - jekyll-feed